/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainDesign;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Hp
 */
public class Transaction extends javax.swing.JFrame {int gt=0;
    int b=0;
int a=0;
int x=2,y=40;
    public  int result;
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
LocalDate localDate = LocalDate.now();
int year  = localDate.getYear();
int month = localDate.getMonthValue();
int day   = localDate.getDayOfMonth();


    /**
     * Creates new form Transaction
     */
    public Transaction() {
        initComponents();
        
        addRow.doClick();
        addRow.setVisible(false);
        lgt.setText("0");
        Connect ct=new Connect();
        
try{
     String sql="Select name from people ";
     ct.st=ct.con.createStatement();
     ct.rs=ct.st.executeQuery(sql);
while(ct.rs.next())
{
    String name=ct.rs.getString("name");
    tc.addItem(name);}
    
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this, e);
   
}

date.setText(dtf.format(localDate));
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tc = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        done = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        date2 = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        addRow = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lgt = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        date = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(400, 100));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Transaction Portal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("T/c By");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 51, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 51, -1, -1));

        getContentPane().add(tc, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 51, 98, -1));

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 90, -1));

        done.setText("Done");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });
        getContentPane().add(done, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 90, -1));

        jButton3.setText("Another T/c");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, -1, -1));

        date2.setText("Type");
        getContentPane().add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 60, 20));

        panel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.lightGray));

        addRow.setText("Add More Row");
        addRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRowActionPerformed(evt);
            }
        });

        jLabel9.setText("Name Of Iteam");

        jLabel10.setText("Rate Per Unit");

        jLabel8.setText("Quantity");

        jLabel11.setText("Total");

        jLabel12.setText("Grand Total");

        lgt.setText("jLabel13");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel12)
                .addGap(27, 27, 27)
                .addComponent(lgt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addGap(34, 34, 34)
                .addComponent(jLabel11)
                .addGap(40, 40, 40)
                .addComponent(addRow)
                .addGap(0, 127, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(addRow))
                .addGap(379, 379, 379)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(lgt)))
        );

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 600, 440));

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Persnal", "Common" }));
        getContentPane().add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 80, -1));

        date.setText("jLabel16");
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 90, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if(done.isEnabled()==true)
{
    Object[] options = { "Yes","No", "Cancel" };
int a=JOptionPane.showOptionDialog(this, "Do you want to done your transation.", "Warning",JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,null, options, options[0]);     
        
if(a==0)
{
    done.doClick();
    this.setVisible(false);      

Main.block=1;
}
if(a==1)
{
    this.setVisible(false);      

Main.block=1;

}


}
        
 else{       
        
        this.setVisible(false);      

Main.block=1;}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
if(Integer.parseInt(lgt.getText())==0)
{
    Object[] options = { "Yes","No", "Cancel" };
int a=JOptionPane.showOptionDialog(this, "There is nothing for transation ", "Warning",
JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,
null, options, options[0]);     
        
if(a==0)
{}
}
else{
Connect cd=new Connect();

try{
   
String t=(tc.getSelectedItem()).toString();

cd.ps=cd.con.prepareStatement("insert into "+(tc.getSelectedItem()).toString()+"(datetime,total,type)values(?,?,?)");
cd.ps.setString(1, dtf.format(localDate));

cd.ps.setString(2, lgt.getText());
cd.ps.setString(3, type.getSelectedItem().toString());
cd.ps.executeQuery();
done.disable();
JOptionPane.showMessageDialog(this, "Transaction Complited");


}
catch(Exception e)
{
JOptionPane.showMessageDialog(this,e);

}
}
        // TODO add your handling code here:
    }//GEN-LAST:event_doneActionPerformed

    private void addRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRowActionPerformed

Connect ct=new Connect();
   
        
        try{
            
            
            ct.st=ct.con.createStatement();
        String sql="Select name from iteam ";
            ct.rs=ct.st.executeQuery(sql);
            
            
            JComboBox c1=new JComboBox();
            JTextField tf1=new JTextField("0");
             JTextField tf2=new JTextField("0");
             JLabel l1=new JLabel ("0");
             JButton b1=new JButton("Done");
             JLabel l2=new JLabel ();
    panel1.add(c1);
    c1.setLocation(x, y);
    c1.setSize(86, 25);
    while(ct.rs.next())
{
    String name=ct.rs.getString("name");
    c1.addItem(name);

}
    panel1.add(tf1);
    tf1.setLocation(x+115, y);
    tf1.setSize(75, 25);
    panel1.add(tf2);
    tf2.setLocation(x+213, y);
    tf2.setSize(67, 25);
    
    if(tf1.getText().isEmpty()==true)
    {
    tf2.disable();
    }
    tf1.addKeyListener(new java.awt.event.KeyListener(){
  
  
                @Override
                public void keyTyped(KeyEvent e) {
                   //To change body of generated methods, choose Tools | Templates.
                }

                @Override
                public void keyPressed(KeyEvent e) {
                     //To change body of generated methods, choose Tools | Templates.
                }

                @Override
                public void keyReleased(KeyEvent e) {int f1,f2;
                    if(tf2.getText().isEmpty()==true)
                    {
                   
                    tf2.setText("0");
                    
                    } 
                    else if(tf1.getText().isEmpty()==true)
                    {
                        f1=0;
                    }  
                    
                    else{f1=Integer.parseInt(tf1.getText());
                        f2=Integer.parseInt(tf2.getText());
                    l1.setText(String.valueOf(f1*f2));
                    
                    }
                    
//To change body of generated methods, choose Tools | Templates.
                }
  });
  
  tf2.addKeyListener(new java.awt.event.KeyListener(){
  
  
                @Override
                public void keyTyped(KeyEvent e) {
                    //To change body of generated methods, choose Tools | Templates.
                }

                @Override
                public void keyPressed(KeyEvent e) {
                     //To change body of generated methods, choose Tools | Templates.
                }

                @Override
                public void keyReleased(KeyEvent e) {int f1,f2;
                    if(tf1.getText().isEmpty()==true)
                    {
                   
                    tf1.setText("0");
                    
                    }
                    else if(tf2.getText().isEmpty()==true)
                    {
                        f2=0;
                    
                    }
                    else{
                        f1=Integer.parseInt(tf1.getText());
                        f2=Integer.parseInt(tf2.getText());
                    l1.setText(String.valueOf(f1*f2));
                    
                    
                    }
//To change body of generated methods, choose Tools | Templates.
                }
  }
  
  
  
  );
    
    panel1.add(l2);
    l2.setLocation(x+442, y);
    l2.setSize(75, 30);
    
    
    
    
        panel1.add(l1);
    l1.setLocation(x+310, y);
    l1.setSize(44, 25);
    panel1.add(b1);
    b1.setLocation(x+365, y);
    b1.setSize(75, 30);
    
    b1.addActionListener(new java.awt.event.ActionListener()
    
    {
                @Override
                public void actionPerformed(ActionEvent e) {
                    if(Integer.parseInt(l1.getText())==0)
                            {Transaction t=new Transaction();
                                JOptionPane.showMessageDialog(t,"Please get complete first");
                            }
                    else{
                    int c=0;
                    
                    Connect cd=new Connect();
                    
                    String name=(tc.getSelectedItem()).toString()+"_"+day+"_"+month+"_"+year;
try{
    String sql="create table "+name+" (par varchar(20),rpu int,hm int,total int)";
    
System.out.println(sql);
cd.st=cd.con.createStatement();
cd.st.executeQuery(sql);
c++;

}
catch(Exception e1)
{
    
    
}
if(c==1)
{try
    
{String sql1="insert into common(dot,name,tablename)values(?,?,?)";
    
cd.ps=cd.con.prepareStatement(sql1);
cd.ps.setString(1, dtf.format(localDate));
cd.ps.setString(2, (tc.getSelectedItem()).toString());
cd.ps.setString(3, name);
cd.ps.executeQuery();
c--;}
catch(Exception k1){
System.out.println(k1);


}



}
try{

cd.ps=cd.con.prepareStatement("insert into  "+name +"(par,rpu,hm,total)values(?,?,?,?)");
cd.ps.setString(1, (c1.getSelectedItem()).toString());
cd.ps.setString(2, tf1.getText());
cd.ps.setString(3, tf2.getText());
cd.ps.setString(4, l1.getText());
cd.ps.executeQuery();}
catch(Exception e1)
{
}
                  ImageIcon img;
        img = new ImageIcon("C:\\Users\\Hp\\Documents\\NetBeansProjects\\JustCheck\\src\\mainDesign\\t1.jpg");
        
        b1.setIcon(img);
        c1.disable();
tf1.disable();
tf2.disable();
l1.disable();
addRow.setVisible(true);
b1.setEnabled(false);//To change body of generated methods, choose Tools | Templates.
  l2.setIcon(img); 
                gt=gt+(Integer.parseInt(l1.getText()));
                lgt.setText(String.valueOf(gt));
                }
                }
    }
    
    );
        
   

        }
        catch(Exception e)
        {
        }






y=y+35;






addRow.setVisible(false);



        // TODO add your handling code here:
    }//GEN-LAST:event_addRowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRow;
    private javax.swing.JLabel date;
    private javax.swing.JLabel date2;
    private javax.swing.JButton done;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lgt;
    private javax.swing.JPanel panel1;
    private javax.swing.JComboBox<String> tc;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
